---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}-env
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env | nindent 2 }}
