---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.agent.endpoints.default.port }}
      targetPort: default
      protocol: TCP
      name: default
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
