#
# Docker buildfile for setting up the remoting agent 
# See copyright notice in the top folder
# See authors file in the top folder
# See license file in the top folder
#

# see https://github.com/eclipse/rdf4j/blob/main/docker/Dockerfile
FROM eclipse/rdf4j-workbench:latest

# Additional Java debugging options
ARG JAVA_TOOL_OPTIONS ""

# TODO Should have a healthcheck
HEALTHCHECK NONE