---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:

