---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  portal.toml: |-
  {{- .Files.Get "resources/portal.toml" | nindent 4 }}
  
  {{- $scope := . }}
  {{- range $asset, $file := .Values.ontologies }}
  {{ $asset }}: |-
  {{- $scope.Files.Get $file | nindent 4 }}
  {{- end }}
  {{- range $endpoint, $binding := .Values.bindings }}
  {{ $endpoint }}.obda: |-
  {{- $binding.mapping | nindent 4 }}
  {{ $endpoint }}.properties: |-
  {{- range $skey, $svalue := $binding.settings }}
    {{ $skey }}: {{ $svalue }}
  {{- end }}
  {{- end }}

