---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $endpoint, $binding := .Values.bindings }}
    - name: {{ $endpoint }}
      port: {{ $binding.port }}
      protocol: TCP
      targetPort: {{ $endpoint }}
  {{- end }}
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
