title="Catena-X Agent Provisioning Demo"

[[tabGroups]]

name="Example Queries"

[[tabGroups.tabs]]

name="Diagnosis Skill"
query="""
PREFIX cx: <https://github.com/catenax-ng/product-knowledge/ontology/cx.ttl#>
PREFIX cx-diag: <https://github.com/catenax-ng/product-knowledge/ontology/diagnosis.ttl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?reason ?code ?description ?version ?partend ?partcat ?partclass WHERE {
  # Select Business Partner
  ?Oem cx:BPNL "BPNL00000003COJN".

  # Search for Trouble Codes of the Business Partner
  # related to a cause in the "Kabelbaum"
  ?Dtc rdf:type cx-diag:DTC.
  ?Dtc cx:provisionedBy ?Oem.
  ?Dtc cx-diag:PossibleCauses ?reason.
  FILTER contains(?reason,"Kabelbaum").
  ?Dtc cx-diag:Code ?code.
  ?Dtc cx-diag:Description ?description.
  ?Dtc cx-diag:Version ?version.

  # Navigate to the affected parts
  # and show only parts with a classification "Powertrain"
  ?Dtc cx-diag:affects ?Part.
  ?Part cx-diag:Category ?partcat.
  ?Part cx-diag:EnDenomination ?partend.
  ?Part cx-diag:Classification ?partclass.
  FILTER contains(?partclass,'Powertrain').

} LIMIT 40
"""